name: Gravity Zero
favicon: null
layout_spectrum: 0.7142428741790354
typography_spectrum: 0.23046791437081993
title: Gravity Zero
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#82b83c'
    - '#7cb63a'
    - '#7eb63d'
    - '#74b92e'
    - '#80b637'
  brandStrength: 0.5
  lightness: 0
  saturation: 0.009226910071447492
  rhythmicContrast: 0.5564330217894167
purpose: []
