title: Gravity Zero
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.5017921
  brandStrength: 1
  rhythmicContrast: 1
  brandColors:
    - '#82b83c'
    - '#7cb63a'
    - '#7eb63d'
    - '#74b92e'
    - '#80b637'
  lightness: 1
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Gravity Zero
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.4265233
layout_spectrum: 0
